resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/Young-china/flight-school
    branch: master
jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
    params:
          private_key: ((my-product-github-private-key))