resources:
- name: flight-school
  type: git
  source:
    uri: git@github.com:Young-china/flight-school.git
    branch: master
    private_key: ((ibm-github-private-key))

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0-rc.1
    uri: git@github.com:Young-china/flight-school.git
    branch: version
    file: version
    private_key: ((ibm-github-private-key))

jobs:
- name: build-rc
  serial_groups: [version]
  plan:
  - get: flight-school
    trigger: true
  - get: version
    params: {pre: rc}
  - task: build-artifact
    file: flight-school/ci/build-artifact.yml
  - put: version
    params: {file: version/number}

- name: integration
  serial: true
  plan:
  - get: flight-school
    trigger: true
    passed: [build-rc]
  - get: version
  - task: integration
    file: flight-school/ci/integration.yml

- name: shipit
  serial_groups: [version]
  plan:
  - get: flight-school
    passed: [integration]
  - get: version
    params: {bump: final}
  - task: promote-to-final
    file: flight-school/ci/build-artifact.yml
  - put: version
    params: {file: version/number}

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    trigger: true
  - put: version
    params: {bump: patch, pre: rc}

- name: major
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: major, pre: rc}

- name: minor
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: minor, pre: rc}